version: "3.9"
services:
  crypto-scanner-mcp:
    build: .
    container_name: crypto-scanner-mcp
    environment:
      TAAPI_KEY: ${TAAPI_KEY}
      CMC_KEY:  ${CMC_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: unless-stopped
